import sys
if not ".." in sys.path:
	sys.path.insert(0,"..")

import module
import random
from datetime import datetime
import util

strategy_cards = [
		"(Organic) machinery",
		"A line has two sides",
		"Abandon desire",
		"Abandon normal instructions",
		"Accept advice",
		"Accretion",
		"Adding on",
		"Allow an easement (an easement is the abandonment of a stricture)",
		"Always first steps",
		"Always give yourself credit for having more than personality",
		"Always the first steps",
		"Are there sections? Consider transitions",
		"Ask people to work against their better judgement",
		"Ask your body",
		"Assemble some of the elements in a group and treat the group",
		"Back up a few steps. What else could you have done?",
		"Balance the consistency principle with the inconsistency principle",
		"Be dirty",
		"Be extravagant",
		"Be less critical more often",
		"Breathe more deeply",
		"Bridges -build -burn",
		"Call your mother and ask her what to do.",
		"Cascades",
		"Change ambiguities to specifics",
		"Change instrument roles",
		"Change nothing and continue with immaculate consistency",
		"Change specifics to ambiguities",
		"Cluster analysis",
		"Consider transitions",
		"Consult other sources -promising -unpromising",
		"Convert a melodic element into a rhythmic element",
		"Courage!",
		"Cut a vital connection",
		"Decorate, decorate",
		"Define an area as `safe' and use it as an anchor",
		"Describe the landscape in which this belongs",
		"Destroy nothing; Destroy the most important thing",
		"Discard an axiom",
		"Disciplined self-indulgence",
		"Disconnect from desire",
		"Discover the recipes you are using and abandon them",
		"Display your talent",
		"Distorting time",
		"Do nothing for as long as possible",
		"Do something boring",
		"Do something sudden, destructive and unpredictable",
		"Do the last thing first",
		"Do the washing up",
		"Do the words need changing?",
		"Do we need holes?",
		"Don't avoid what is easy",
		"Don't be afraid of things because they're easy to do",
		"Don't be frightened of cliches",
		"Don't be frightened to display your talents",
		"Don't break the silence",
		"Don't stress one thing more than another",
		"Emphasize differences",
		"Emphasize repetitions",
		"Emphasize the flaws",
		"Faced with a choice, do both",
		"Find a safe part and use it as an anchor",
		"First work alone, then work in unusual pairs",
		"From nothing to more than nothing",
		"Get your neck massaged",
		"Ghost echoes",
		"Give the game away",
		"Give way to your worst impulse",
		"Go outside. Shut the door.",
		"Go slowly all the way round the outside",
		"Go to an extreme, move back to a more comfortable place",
		"How would someone else do it?",
		"How would you explain this to your parents?",
		"How would you have done it?",
		"Humanize something that is free of error.",
		"Idiot glee (?)",
		"In total darkness, or in a very large room, very quietly",
		"Infinitesimal gradations",
		"Instead of changing the thing, change the world around it",
		"Intentions -credibility of -nobility of -humility of",
		"Into the impossible",
		"Is it finished?",
		"Is something missing?",
		"Is the style right?",
		"Is there something missing?",
		"It is quite possible (after all)",
		"It is simply a matter of work",
		"Just carry on",
		"List the qualities it has. List those you'd like.",
		"Listen in total darkness, or in a very large room, very quietly",
		"Listen to the quiet voice",
		"Look at a very small object, look at its centre",
		"Look at the order in which you do things",
		"Look closely at the most embarrassing details and amplify.",
		"Lost in useless territory",
		"Magnify the most difficult details",
		"Make a blank valuable by putting it in an exquisite frame",
		"Make a sudden, destructive unpredictable action; incorporate",
		"Make an exhaustive list of everything you might do and do the last thing on the list",
		"Make it more sensual",
		"Make what's perfect more human",
		"Mechanize something idiosyncratic",
		"Move towards the unimportant",
		"Mute and continue",
		"Not building a wall but making a brick",
		"Once the search has begun, something will be found",
		"Only a part, not the whole",
		"Only one element of each kind",
		"Overtly resist change",
		"Pae White's non-blank graphic metacard",
		"Pay attention to distractions",
		"Picture of a man spotlighted",
		"Put in earplugs",
		"Question the heroic approach",
		"Remember those quiet evenings",
		"Remove a restriction",
		"Remove ambiguities and convert to specifics",
		"Remove specifics and convert to ambiguities",
		"Remove the middle, extend the edges",
		"Repetition is a form of change",
		"Retrace your steps",
		"Revaluation (a warm feeling)",
		"Reverse",
		"Short circuit (example; a man eating peas with the idea that they will improve his virility shovels them straight into his lap)",
		"Shut the door and listen from outside",
		"Simple subtraction",
		"Simply a matter of work",
		"Slow preparation, fast execution",
		"Spectrum analysis",
		"State the problem in words as simply as possible",
		"Steal a solution.",
		"Take a break",
		"Take away as much mystery as possible. What is left?",
		"Take away the elements in order of apparent non-importance",
		"Take away the important parts",
		"Tape your mouth",
		"The inconsistency principle",
		"The most important thing is the thing most easily forgotten",
		"Think -inside the work -outside the work",
		"Think of the radio",
		"Tidy up",
		"Towards the insignificant",
		"Trust in the you of now",
		"Try faking it",
		"Turn it upside down",
		"Twist the spine",
		"Use \"unqualified\" people.",
		"Use an old idea",
		"Use an unacceptable color",
		"Use cliches",
		"Use fewer notes",
		"Use filters",
		"Use something nearby as a model",
		"Use your own ideas",
		"Voice your suspicions",
		"Water",
		"What are the sections sections of? Imagine a caterpillar moving",
		"What context would look right?",
		"What do you do? Now, what do you do best?",
		"What else is this like?",
		"What is the reality of the situation?",
		"What is the simplest solution?",
		"What mistakes did you make last time?",
		"What most recently impressed you? How is it similar? What can you learn from it? What could you take from it?",
		"What to increase? What to reduce? What to maintain?",
		"What were the branch points in the evolution of this entity",
		"What were you really thinking about just now? Incorporate",
		"What would make this really successful?",
		"What would your closest friend do?",
		"What wouldn't you do?",
		"When is it for? Who is it for?",
		"Where is the edge?",
		"Which parts can be grouped?",
		"Who would make this really successful?",
		"Work at a different speed",
		"Would anyone want it?",
		"You are an engineer",
		"You can only make one dot at a time",
		"You don't have to be ashamed of using your own ideas",
		"Your mistake was a hidden intention"
]

@module.type("PRIVMSG")
@module.regex(r"_BOTNAMES_:?,?\ ?i need a strategy")
def oblique(bot,message,regex_matches=None):
	user = message.sender
	if bot.getcustom("asleep"):
		additions = ["Consider a nap","What would it look like in a dream?","Imagine it sleeping","Drink a glass of warm milk"]
		if util.chance(0.2):
			bot.commands.action(message.replyto,"snores")
			return
	else:
		additions = []
	if not bot.getcustom("oblique_picks"):
		bot.setcustom("oblique_picks",{})
	o = bot.getcustom("oblique_picks")
	this_week = datetime.today().strftime("%Y%W")
	if not this_week in o.keys():
		o[this_week] = {}
	if not user in o[this_week].keys():
		o[this_week][user] = random.choice(strategy_cards+additions)
	selection = o[this_week][user]
	bot.commands.privmsg(message.replyto,"{user}: {card}".format(user=user,card=selection),True)

strategies = module.Module("strategies")
strategies.add_function(oblique)
